# Generated by Django 4.2.5 on 2023-09-28 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0003_alter_business_options_businesslink'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_threshold', models.IntegerField(default=0)),
                ('contents', models.TextField(blank=True, null=True)),
                ('rating_label', models.CharField(blank=True, max_length=120, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aormobile.business')),
            ],
        ),
    ]
