# Generated by Django 4.2.5 on 2023-09-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0004_businesscontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslink',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslink',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
