# Generated by Django 4.2.5 on 2023-09-28 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0009_businessreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
