# Generated by Django 4.2.5 on 2023-09-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0014_mailsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
