# Generated by Django 4.2.5 on 2023-09-28 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0015_businessindustry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessindustry',
            options={'verbose_name_plural': 'business industries'},
        ),
        migrations.AddField(
            model_name='business',
            name='business_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aormobile.businessindustry'),
        ),
    ]
