# Generated by Django 4.2.5 on 2023-09-28 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0017_messagetemplate_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsetting',
            name='confirmation_template',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailsetting',
            name='sms_confirmation_template',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailsetting',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
