# Generated by Django 4.2.5 on 2023-09-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0018_mailsetting_confirmation_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitation_type',
            field=models.CharField(choices=[('Single', 'single'), ('Bulk', 'bulk'), ('Mail', 'mail')], default='single', max_length=20),
        ),
    ]
