# Generated by Django 4.2.5 on 2023-09-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0019_invitation_number_alter_invitation_invitation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessreview',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
