# Generated by Django 4.2.5 on 2023-09-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0020_businessreview_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('capasity', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
