# Generated by Django 4.2.5 on 2023-09-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0021_smsplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsplan',
            old_name='capasity',
            new_name='capacity',
        ),
        migrations.AlterField(
            model_name='smsplan',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
