# Generated by Django 4.2.5 on 2023-09-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0023_smssubcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smsplan',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
