# Generated by Django 4.2.5 on 2023-09-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0025_messagetemplate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smssubcription',
            name='credits',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
