# Generated by Django 4.2.5 on 2023-09-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0026_alter_smssubcription_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='smssubcription',
            name='payer_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='smssubcription',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='smssubcription',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
