# Generated by Django 4.2.5 on 2023-09-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0027_smssubcription_payer_id_smssubcription_payment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_or_region', models.CharField(max_length=200)),
                ('iso_code', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
                ('area_code', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
