# Generated by Django 4.2.5 on 2023-09-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0030_business_current_credits_business_email_sender_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smssubcription',
            name='chargebee_plan_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
