# Generated by Django 4.2.5 on 2023-09-28 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0034_alter_invitation_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderEmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_reminder_sent', models.BooleanField(default=False)),
                ('is_secondary_reminder_sent', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aormobile.business')),
            ],
        ),
    ]
