# Generated by Django 4.2.5 on 2023-09-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0035_reminderemailhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderemailhistory',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
