# Generated by Django 4.2.5 on 2023-09-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0037_business_email_subject_customerreminderhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_limit', models.FloatField()),
                ('sms_credit', models.FloatField()),
                ('remaining_credit', models.FloatField()),
                ('about_to_reach_reminder', models.BooleanField(default=False)),
                ('is_reached_reminder', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
