# Generated by Django 4.2.5 on 2023-09-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0038_aws'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitation_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
