# Generated by Django 4.2.5 on 2023-09-28 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aormobile', '0039_invitation_invitation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessreview',
            name='invitation_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SNSTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_arn', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
