# Generated by Django 4.2.5 on 2023-09-28 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0042_businessreview_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNSTopicSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_arn', models.CharField(max_length=200, unique=True)),
                ('subscription_arn', models.CharField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sns_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aormobile.snstopic')),
            ],
        ),
    ]
