# Generated by Django 4.2.5 on 2023-09-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0043_snstopicsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snstopicsubscription',
            name='endpoint_arn',
            field=models.CharField(max_length=200),
        ),
    ]
