# Generated by Django 4.2.5 on 2023-09-28 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aormobile', '0045_scheduleinvitation_scheduleinvitationdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_schedule_invitation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='schedule_invitation_date_status_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='schedule_invitation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleinvitationdate',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ScheduleInvitationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.JSONField()),
                ('email_sender_name', models.TextField(blank=True, null=True)),
                ('email_subject', models.TextField(blank=True, null=True)),
                ('sms_sender_id', models.TextField(blank=True, null=True)),
                ('slug_id', models.IntegerField()),
                ('slug', models.TextField()),
                ('template', models.TextField()),
                ('template_id', models.IntegerField()),
                ('url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('schedule_invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aormobile.scheduleinvitation')),
            ],
        ),
    ]
